import { createClient } from "@/lib/supabase/server";
import { ReportsAnalysis } from "@/components/reports/ReportsAnalysis";

export default async function ReportsPage() {
    const supabase = await createClient();

    // Fetch Invoices (Sales)
    const { data: invoices } = await supabase
        .from('invoices')
        .select('total_amount, created_at, paid_amount')
        .order('created_at', { ascending: true });

    // Fetch Expenses
    const { data: expenses } = await supabase
        .from('roi_expenses')
        .select('amount, expense_type, date')
        .order('date', { ascending: true });

    // Process Data Grouped by Month
    const monthlyStats = new Map<string, { sales: number; expenses: number; adCost: number }>();

    // Helper to get Month Year key
    const getMonthKey = (dateStr: string) => {
        const date = new Date(dateStr);
        return date.toLocaleString('default', { month: 'short', year: 'numeric' });
    };

    // Process Invoices
    (invoices || []).forEach(inv => {
        const key = getMonthKey(inv.created_at);
        const current = monthlyStats.get(key) || { sales: 0, expenses: 0, adCost: 0 };
        // Assuming paid_amount acts as realized revenue for P&L, or total_amount for Accrual. 
        // User asked for "Revenue = Actual Sold * Selling Price", which maps to total_amount unless unpaid.
        // Let's use total_amount here for Sales figures.
        current.sales += Number(inv.total_amount || 0);
        monthlyStats.set(key, current);
    });

    // Process Expenses
    (expenses || []).forEach(exp => {
        const key = getMonthKey(exp.date);
        const current = monthlyStats.get(key) || { sales: 0, expenses: 0, adCost: 0 };
        const amount = Number(exp.amount || 0);
        current.expenses += amount;
        if (exp.expense_type === 'ad_cost') {
            current.adCost += amount;
        }
        monthlyStats.set(key, current);
    });

    // Convert map to array and calculate profit
    const monthlyData = Array.from(monthlyStats.entries()).map(([month, data]) => ({
        month,
        sales: data.sales,
        expenses: data.expenses,
        profit: data.sales - data.expenses, // Simplified: Sales - Operating Exp (COGS should ideally be subtracted too)
        adCost: data.adCost
    }));

    // Calculate Totals
    const totalSales = monthlyData.reduce((sum, d) => sum + d.sales, 0);
    const totalExpenses = monthlyData.reduce((sum, d) => sum + d.expenses, 0);
    const totalAdSpend = monthlyData.reduce((sum, d) => sum + d.adCost, 0);
    const netProfit = totalSales - totalExpenses; // Note: COGS missing here as per previous step, needs to be integrated later for true Net Profit

    // ROI = (Return / Investment) * 100
    // Here we consider "Return" as Net Profit (or Gross Profit generated by Ads)
    // and "Investment" as Ad Spend.
    // If Ad Spend is 0, avoid division by zero.
    const roi = totalAdSpend > 0 ? (netProfit / totalAdSpend) * 100 : 0;

    const summary = {
        totalSales,
        totalExpenses,
        netProfit,
        totalAdSpend,
        roi
    };

    return (
        <div className="space-y-8 p-4 md:p-8 pt-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">রিপোর্ট (Reports)</h1>
                    <p className="text-muted-foreground mt-1">
                        মাসিক লাভ-ক্ষতি এবং ROI বিশ্লেষণ।
                    </p>
                </div>
            </div>

            <ReportsAnalysis monthlyData={monthlyData} summary={summary} />
        </div>
    );
}
